export const PULSEVAULT_ABI = [
  "function registerPublicKey(bytes pubKey)",
  "function createVault(address beneficiary, address[] guardians, uint8 threshold, uint64 interval, uint64 gracePeriod, string cid, bytes[] encryptedGuardianShares)",
  "function checkIn()",
  "function castVote(address owner, bool confirm, bytes shareForBeneficiary)",
  "function rekey(string newCid, bytes[] newEncryptedGuardianShares)",
  "function getVault(address owner) view returns (address beneficiary, address[] guardians, uint8 threshold, uint64 interval, uint64 gracePeriod, string cid, bytes[] encryptedGuardianShares, uint64 lastCheckIn, uint64 round, bool released)",
  "function getGuardianShare(address owner, address guardian) view returns (bytes)",
  "function getReleasedShares(address owner) view returns (bytes[])",
  "function getVotes(address owner) view returns (uint8 confirms, uint8 rejects, address[] voters)",
  "function statusOf(address owner) view returns (uint8)",
  "function secondsUntilExpiry(address owner) view returns (uint64)",
  "function publicKeyOf(address account) view returns (bytes)",
  "function vaultsAsGuardian(address account, uint256 index) view returns (address)",
  "function vaultsAsBeneficiary(address account, uint256 index) view returns (address)",
  "event PublicKeyRegistered(address indexed account, bytes pubKey)",
  "event VaultCreated(address indexed owner, address indexed beneficiary, address[] guardians, uint8 threshold, uint64 interval, uint64 gracePeriod, string cid)",
  "event CheckedIn(address indexed owner, uint64 round)",
  "event VoteCast(address indexed owner, address indexed guardian, bool confirm, uint64 round)",
  "event VaultReleased(address indexed owner, address indexed beneficiary)",
  "event Rekeyed(address indexed owner, string cid, uint64 round)",
  "error VaultAlreadyExists()",
  "error VaultNotFound()",
  "error AlreadyReleased()",
  "error NotOwner()",
  "error NotGuardian()",
  "error NotBeneficiary()",
  "error InvalidGuardians()",
  "error InvalidThreshold()",
  "error InvalidInterval()",
  "error InvalidBeneficiary()",
  "error InvalidSharesLength()",
  "error NotInVoting()",
  "error AlreadyVoted()",
  "error EmptyShareForConfirm()",
  "error NotReleased()",
];

export const STATUS = ["None", "Active", "Grace", "Voting", "Released"];
